### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by aaronahearne** [optimistdigital/nova-multiselect-field#54] opened 2020-07-30 08:21 UTC
All of my multiselects have stopped working, displaying an error in the console. Using the example code produces the same error.

nova-multiselect-field version: 1.9.1
Nova version: 3.8.2
PHP version: 7.4.3
Laravel version: 7.10.3

![image](https://user-images.githubusercontent.com/5104743/88899336-d1a43f00-d245-11ea-8a17-eef3e4c6824c.png)

![image](https://user-images.githubusercontent.com/5104743/88899358-d963e380-d245-11ea-92d6-fb5d0ebf2570.png)

**Comment by Tarpsvo** [comment] 2020-07-30 08:31
Duplicate of #51. Revert to Nova 3.7.X or wait for 3.8.3 with fix. This is an issue with Laravel Nova.

**Closed by Tarpsvo** 2020-07-30 08:31 UTC

**Comment by iSenne85** [comment] 2020-08-28 10:20
Version 3.8.4 does not fix the message `Cannot read property 'toUpperCase' of undefined`, but the multiselects are working again in this version
